### ISSUE TITLE
Sinks: filter by tags is not filtering

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#1577]
Even after including the tag filter in the sink, sinks without the filtered tag are displayed in the list:

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/584822c1-8da1-4c36-996c-74431e0c20d5)

**Comment by gpazuch** [comment]
@manrodrigues cannot reproduce.
this issue may have been resolved on previous work

**Comment by manrodrigues** [comment]
@gpazuch i'm still not able to filter sinks by tags
![image](https://user-images.githubusercontent.com/78241475/182891752-6312208f-3606-46a5-a994-e50f703355e5.png)

**Comment by gpazuch** [comment]
I just tested this in develop and it seemed to be working.

**Comment by manrodrigues** [comment]
![image](https://user-images.githubusercontent.com/78241475/183449619-9625105d-029c-49dc-b162-bc2f3b087c1c.png)

![image](https://user-images.githubusercontent.com/78241475/183449713-fb8441b4-b996-4625-a533-cd60906d49d3.png)

**Comment by manrodrigues** [comment]
@gpazuch  we need to figure out why the behavior is not consistent.. it's not working anymore..

you can use the API to filter like

`{{orb_live_url}}api/v1/sinks?tags={"my":"tag"}`

![image](https://user-images.githubusercontent.com/78241475/200372124-5ba549ec-a088-44bc-bd94-456f1b36e650.png)
